# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
one_D_Aray = np.array([1,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
two_D_Array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

# Create a 3-dimensional Numpy array using np.array()
three_D_Array = np.array([
    [
        [1,2,4],
        [5,6,7]
    ],
    [
        [3,8,9],
        [10,11,12]
    ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_D_Aray.shape, one_D_Aray.dtype, one_D_Aray.size, type(one_D_Aray)

((4,), dtype('int32'), 4, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
two_D_Array.shape, two_D_Array.dtype, two_D_Array.size, type(two_D_Array)

((2, 5), dtype('int32'), 10, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
three_D_Array.shape, three_D_Array.dtype, three_D_Array.size, type(three_D_Array)

((2, 2, 3), dtype('int32'), 12, numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(two_D_Array)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [12]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_int_array = np.random.randint(0,10,size=(7,2))
random_int_array

array([[7, 4],
       [2, 9],
       [3, 8],
       [1, 2],
       [6, 7],
       [3, 3],
       [0, 2]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random((3,5))
random_float_array

array([[0.4731483 , 0.38792068, 0.7996123 , 0.5132603 , 0.85631398],
       [0.52909292, 0.42859374, 0.68267764, 0.96376118, 0.74525713],
       [0.84608491, 0.42871222, 0.66266918, 0.81582813, 0.30430678]])

In [33]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_0_to_10 = np.random.randint(0,10,size=(4,6))
random_0_to_10

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_1_to_10 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_1_to_10)

In [37]:
# Find the 0'th index of the latest array you created
random_1_to_10[0]

array([2, 5, 8, 9, 9, 1, 9])

In [39]:
# Get the first 2 rows of latest array you created
random_1_to_10[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
random_1_to_10[:2,:2]

array([[2, 5],
       [7, 9]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array1 = np.random.randint(0,10,size=(3,5))
array2 = np.random.randint(0,10,size=(3,5))
array1

array([[4, 0, 2, 9, 7],
       [5, 7, 8, 3, 0],
       [0, 9, 3, 6, 1]])

In [47]:
array2

array([[2, 0, 4, 0, 7],
       [0, 0, 1, 1, 5],
       [6, 4, 0, 0, 2]])

In [48]:
# Add the two arrays together
array1 + array2

array([[ 6,  0,  6,  9, 14],
       [ 5,  7,  9,  4,  5],
       [ 6, 13,  3,  6,  3]])

In [44]:
# Create another array of ones of shape (5, 3)
new_ones_array = np.ones((5,3))
new_ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# Try add the array of ones and the other most recent array together
array1 + new_ones_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

By Transposing one of the arrays

In [51]:
array1.T + new_ones_array

array([[ 5.,  6.,  1.],
       [ 1.,  8., 10.],
       [ 3.,  9.,  4.],
       [10.,  4.,  7.],
       [ 8.,  1.,  2.]])

In [53]:
# Create another array of ones of shape (3, 5)
ones_array_3x5 = np.ones((3, 5))
ones_array_3x5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Subtract the new array of ones from the other most recent array
array1 - ones_array_3x5

array([[ 3., -1.,  1.,  8.,  6.],
       [ 4.,  6.,  7.,  2., -1.],
       [-1.,  8.,  2.,  5.,  0.]])

In [57]:
# Multiply the ones array with the latest array
array1 * ones_array_3x5

array([[4., 0., 2., 9., 7.],
       [5., 7., 8., 3., 0.],
       [0., 9., 3., 6., 1.]])

In [59]:
# Take the latest array to the power of 2 using '**'
array1 ** 2

array([[16,  0,  4, 81, 49],
       [25, 49, 64,  9,  0],
       [ 0, 81,  9, 36,  1]], dtype=int32)

In [60]:
# Do the same thing with np.square()
np.square(array1)

array([[16,  0,  4, 81, 49],
       [25, 49, 64,  9,  0],
       [ 0, 81,  9, 36,  1]], dtype=int32)

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(array1)

4.266666666666667

In [62]:
# Find the maximum of the latest array using np.max()
np.max(array1)

9

In [63]:
# Find the minimum of the latest array using np.min()
np.min(array1)

0

In [64]:
# Find the standard deviation of the latest array
np.std(array1)

3.172100600898752

In [65]:
# Find the variance of the latest array
np.var(array1)

10.062222222222223

In [66]:
# Reshape the latest array to (3, 5, 1)
array1.reshape((3, 5, 1))

array([[[4],
        [0],
        [2],
        [9],
        [7]],

       [[5],
        [7],
        [8],
        [3],
        [0]],

       [[0],
        [9],
        [3],
        [6],
        [1]]])

In [67]:
# Transpose the latest array
array1.T

array([[4, 5, 0],
       [0, 7, 9],
       [2, 8, 3],
       [9, 3, 6],
       [7, 0, 1]])

What does the transpose do?

It swaps the rows and columns of an array

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_3X3 = np.random.randint(0,10,size=(3,3))
array_3X2 = np.random.randint(0,10,size=(3,2))
array_3X3

array([[2, 2, 3],
       [6, 3, 8],
       [0, 7, 6]])

In [71]:
array_3X2

array([[1, 7],
       [0, 8],
       [8, 1]])

In [72]:
# Perform a dot product on the two newest arrays you created
np.dot(array_3X3,array_3X2)

array([[26, 33],
       [70, 74],
       [48, 62]])

In [73]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_4X3_1 = np.random.randint(0,10,size=(4,3))
array_4X3_2 = np.random.randint(0,10,size=(4,3))
array_4X3_1

array([[6, 9, 2],
       [6, 9, 8],
       [3, 0, 1],
       [0, 4, 4]])

In [74]:
array_4X3_2

array([[6, 8, 8],
       [2, 2, 2],
       [3, 7, 5],
       [7, 0, 7]])

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(array_4X3_1,array_4X3_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

By transposing one of the two arrays

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_4X3_1.T, array_4X3_2)

array([[ 57,  81,  75],
       [100,  90, 118],
       [ 59,  39,  65]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [77]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_4X2_1 = np.random.randint(0,10,size=(4,2))
array_4X2_2 = np.random.randint(0,10,size=(4,2))
array_4X2_1

array([[3, 0],
       [7, 3],
       [5, 7],
       [3, 2]])

In [78]:
array_4X2_2

array([[8, 2],
       [8, 1],
       [1, 1],
       [5, 2]])

In [79]:
# Compare the two arrays with '>'
array_4X2_1 > array_4X2_2

array([[False, False],
       [False,  True],
       [ True,  True],
       [False, False]])

What happens when you compare the arrays with `>`?

It return a numpy array of boolean values

In [80]:
# Compare the two arrays with '>='
array_4X2_1 >= array_4X2_2

array([[False, False],
       [False,  True],
       [ True,  True],
       [False,  True]])

In [84]:
# Find which elements of the first array are greater than 7
array_4X2_1[array_4X2_1 > 7]

array([], dtype=int32)

In [88]:
# Which parts of each array are equal? (try using '==')
array_4X2_1 == array_4X2_2

array([[False, False],
       [False, False],
       [False, False],
       [False,  True]])

In [89]:
array_4X2_1

array([[3, 0],
       [7, 3],
       [5, 7],
       [3, 2]])

In [86]:
# Sort one of the arrays you just created in ascending order
np.sort(array_4X2_1)

array([[0, 3],
       [3, 7],
       [5, 7],
       [2, 3]])

In [93]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_4X2_1)

array([[1, 0],
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_4X2_1)

2

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_4X2_1)

1

In [96]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_4X2_1,axis=1)

array([0, 0, 1, 0], dtype=int64)

In [95]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_4X2_1,axis=0)

array([0, 0], dtype=int64)

In [98]:
# Create an array of normally distributed random numbers
Normal_dist_array = np.random.rand(100)
Normal_dist_array

array([0.22426931, 0.71217922, 0.23724909, 0.3253997 , 0.74649141,
       0.6496329 , 0.84922341, 0.65761289, 0.5683086 , 0.09367477,
       0.3677158 , 0.26520237, 0.24398964, 0.97301055, 0.39309772,
       0.89204656, 0.63113863, 0.7948113 , 0.50263709, 0.57690388,
       0.49251769, 0.19524299, 0.72245212, 0.28077236, 0.02431597,
       0.6454723 , 0.17711068, 0.94045858, 0.95392858, 0.91486439,
       0.3701587 , 0.01545662, 0.92831856, 0.42818415, 0.96665482,
       0.96361998, 0.85300946, 0.29444889, 0.38509773, 0.85113667,
       0.31692201, 0.16949275, 0.55680126, 0.93615477, 0.6960298 ,
       0.57006117, 0.09717649, 0.61500723, 0.99005385, 0.14008402,
       0.51832965, 0.87737307, 0.74076862, 0.69701574, 0.70248408,
       0.35949115, 0.29359184, 0.80936116, 0.81011339, 0.86707232,
       0.91324055, 0.5113424 , 0.50151629, 0.79829518, 0.64996393,
       0.70196688, 0.79579267, 0.89000534, 0.33799516, 0.37558295,
       0.09398194, 0.57828014, 0.03594227, 0.46559802, 0.54264

In [101]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1,100,10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.